# Generated by Django 4.1.2 on 2023-02-02 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'attribute',
                'verbose_name_plural': 'attributes',
                'db_table': 'attributes',
            },
        ),
        migrations.CreateModel(
            name='AttributeAndValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.attribute')),
            ],
            options={
                'verbose_name': 'attributes_and_value',
                'verbose_name_plural': 'attributes_and_values',
                'db_table': 'attributes_and_value',
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('authuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('patronymic', models.CharField(blank=True, max_length=150)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('invite_code', models.CharField(max_length=20, null=True)),
                ('attributes', models.ManyToManyField(to='users.attribute')),
            ],
            options={
                'verbose_name': 'coordinator',
                'verbose_name_plural': 'coordinators',
                'db_table': 'coordinators',
            },
            bases=('authenticate.authuser', models.Model),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('authuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('patronymic', models.CharField(blank=True, max_length=150)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('attributes', models.ManyToManyField(through='users.AttributeAndValue', to='users.attribute')),
                ('coordinator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coor', to='users.coordinator')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
                'db_table': 'players',
            },
            bases=('authenticate.authuser', models.Model),
        ),
        migrations.AddField(
            model_name='attributeandvalue',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player'),
        ),
    ]
