# Generated by Django 4.1.2 on 2023-03-15 10:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_coordinator_company_coordinator_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU'),
        ),
    ]
