# Generated by Django 4.1.2 on 2023-02-19 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_coordinator_company_coordinator_job_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('coordinator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coordinator')),
            ],
        ),
        migrations.CreateModel(
            name='GameAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.ManyToManyField(to='users.attribute')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_game.game')),
            ],
        ),
    ]
