# Generated by Django 4.1.2 on 2023-03-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'bs_game', 'verbose_name_plural': 'bs_games'},
        ),
        migrations.AlterModelOptions(
            name='gameattributes',
            options={'verbose_name': 'bs_attribute', 'verbose_name_plural': 'bs_attributes'},
        ),
        migrations.AlterModelTable(
            name='game',
            table='bs_game',
        ),
        migrations.AlterModelTable(
            name='gameattributes',
            table='bs_attributes',
        ),
    ]
