# Generated by Django 4.1.2 on 2023-03-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_game', '0002_alter_game_options_alter_gameattributes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
    ]
