# Generated by Django 4.1.2 on 2023-04-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_game', '0003_game_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
